global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  #static_map: true
  
  rolling_window: false
  resolution: 0.05
  
  transform_tolerance: 1.0
  ##map_type: costmap
  ##map_type: voxel
  ##inflation_radius: 0.1
  plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

